---
# Configuration files
- name: Backup original {{ item.file }}
  copy: 
    src: /etc/php/7.1/{{ item.file }}
    dest: /etc/php/7.1/{{ item.file }}.original
    remote_src: yes
    force: no
- name: Fetch original {{ item.file }}
  fetch:
    src: /etc/php/7.1/{{ item.file }}.original
    dest: roles/portal/files/{{ item.file }}
    flat: yes
  when: setup_type == 'local'
- name: Upload custom {{ item.file }}
  template: 
    src: '{{ item.file }}.j2'
    dest: /etc/php/7.1/{{ item.file }}
