---

- name: Create Drupal cron log directory
  file:
    path: /var/log/xtuple/cron
    state: directory

- name: Setup Drupal cron
  cron:
    name: 'Drupal {{ item.name }} cron'
    minute: '{{ item.minute }}'
    user: '{{ deployer_name }}'
    job: 'sudo -u www-data sh -c "cd /opt/xtuple/portal/{{ item.name }} && ./console.php cron:run" >> /var/log/xtuple/cron/{{ item.name }}.log 2>&1'
  with_items:
    - name: dev
      minute: 30
    - name: stage
      minute: 15
    - name: live
      minute: 0
  when: setup_type == 'server'
