---

postgres_clusters:
  - name: xtuple
    version: 9.6
    port: 5432
    locale: '{{ locale }}'
    start_conf: auto # auto | manual | disabled
    databases:
      - name: '{{ deployer_name }}'
        user: '{{ deployer_name }}'
        password: '{{ deployer_pass }}'
      - name: phpunit
        user: phpunit
        password: phpunit
      - name: erp
        user: admin
        password: admin
