---
# Vagrant-specific provision tasks.
- name: Create xTuple ERP private keys directory
  file:
    path: /var/xtuple
    state: directory
    mode: 0755

- name: Check if /vagrant/var/keys exists
  stat:
    path: /vagrant/var/keys
  register: vagrant_xtuple_keys_dir

- block:
  - name: Check if /var/xtuple/keys exists
    stat:
      path: /var/xtuple/keys
    register: var_xtuple_keys_dir
  - name: Symlink Vagrant keys directory
    file:
      src: /vagrant/var/keys
      path: /var/xtuple/keys
      state: link
    when: not var_xtuple_keys_dir.stat.exists
  - name: Match host username for shared directories
    stat:
      path: /opt/xtuple/commerce
    register: dir
    when:
  - name: Adjust shared directories owner
    user:
      name: '{{ host.username }}'
      createhome: no
      uid: '{{ dir.stat.uid }}'
      group: '{{ dir.stat.gr_name }}'
    when: dir.stat.gr_name is defined
  when: setup_type == 'local' and vagrant_xtuple_keys_dir.stat.exists
