---
# Common tasks for all installations.
- name: Set timezone to {{ timezone }}
  timezone:
    name: '{{ timezone }}'
  notify:
  - Restart Cron
- name: Set locale to {{ locale }}
  locale_gen:
    name: '{{ locale }}'
- name: Add git-core/ppa repository
  apt_repository:
    repo: 'ppa:git-core/ppa'
- name: Install basic software
  apt:
    name: '{{ item.apt }}'
    state: latest
  with_items:
    - name: Git
      apt: git
    - name: Vim
      apt: vim
    - name: Make
      apt: make
    - name: gcc
      apt: gcc
    - name: g++
      apt: g++
    - name: NTP
      apt: ntp
    - name: Pip
      apt: python3-pip
