---
# Common tasks that should be run for all installations.

- name: Setup locale
  import_tasks: locale.yml

- name: Setup timezone
  import_tasks: timezone.yml

- name: Install Git
  import_tasks: git.yml

- name: Install basic software packages
  apt:
    name: '{{ item.apt }}'
    state: latest
  loop: '{{ packages|flatten(levels=1) }}'

- name: Setup deployment user
  import_tasks: deployer.yml

- name: Setup ZSH
  import_tasks: zsh.yml
  when: deployer_shell == 'zsh'

- name: Setup Postfix
  import_tasks: postfix.yml
  when: postfix
