---

php_packages:
  - apt: php-common
  - apt: php7.1-common
  - apt: php7.1-json
  - apt: php7.1-opcache
  - apt: php7.1-readline
  - apt: php7.1-fpm
  - apt: php7.1
  - apt: php7.1-xml
  - apt: php7.1-dev
  - apt: php7.1-gd
  - apt: php7.1-pgsql
  - apt: php7.1-curl
  - apt: php7.1-intl
  - apt: php7.1-mcrypt
  - apt: php7.1-mbstring
  - apt: php7.1-soap
  - apt: php7.1-zip

php_phars:
  - name: Composer
    bin: composer
    version: 1.7.0
    url: https://getcomposer.org/download/1.8.0/composer.phar
    checksum: sha256:0901a84d56f6d6ae8f8b96b0c131d4f51ccaf169d491813d2bcedf2a6e4cefa6
  - name: Phing
    bin: phing
    version: 2.16.1
    url: http://www.phing.info/get/phing-2.16.1.phar
    checksum: sha512:fc3ec05b6540642f4aa33e219d08b9c850eb0dc3921acf171b5055e07e62d06d934d6cd32e7b5bdfdd6a13a53acd600eaa36f8f19a37bb835919e339abd103af

php_pears:
  - name: VersionControl_Git-0.5.0

php_composer:

php_ini:
  max_execution_time: 60
  memory_limit: 256M
  max_input_vars: 100000
  pcre:
    backtrack_limit: 10000000

ruby_apt_packages:
  - rubygems
  - rubygems-integration
  - ruby-dev

ruby_gems:
  - name: Compass
    gem: compass
  - name: ASCIIDoctor
    gem: asciidoctor
  - name: CodeRay (for ASCIIDoctor)
    gem: coderay
