---

- name: Add Postgres user {{ database.user }}
  become: true
  become_user: postgres
  postgresql_user:
    name: '{{ database.user }}'
    password: '{{ database.password }}'
    port: '{{ item.port }}'

- name: Add Postgres database {{ database.name }} (owner {{ database.user }})
  become: true
  become_user: postgres
  postgresql_db:
    name: '{{ database.name }}'
    owner: '{{ database.user }}'
    port: '{{ item.port }}'
