---

- name: Include setup-specific variables
  include_vars: '{{ setup_type }}.yml'

- name: Add Postgres repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
- name: Add Postgres apt key
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Install postgresql-common
  apt:
    name: postgresql-common
    update_cache: yes
    state: latest
- name: Backup original createcluster.conf
  copy:
    src: /etc/postgresql-common/createcluster.conf
    dest: /etc/postgresql-common/createcluster.conf.original
    remote_src: yes
    force: no
- name: Fetch original createcluster.conf
  fetch:
    src: /etc/postgresql-common/createcluster.conf.original
    dest: roles/postgres/files/common/createcluster.conf
    flat: yes
  when: setup_type == 'local'
- name: Upload custom createcluster.conf
  template:
    src: common/createcluster.conf.j2
    dest: /etc/postgresql-common/createcluster.conf
  notify: Restart Postgres

- name: Install Postgres {{ postgres_version }}
  apt:
    name:
      - postgresql-{{ postgres_version }}
      - postgresql-client-{{ postgres_version }}
      - postgresql-contrib-{{ postgres_version }}
      - postgresql-server-dev-{{ postgres_version }}
    state: latest

- name: Install Python psycopg2 library
  pip:
    name: psycopg2-binary

- name: Install plv8
  include_tasks: plv8.yml

- name: Create database clusters
  include_tasks: cluster.yml
  with_items: '{{ postgres_clusters }}'
