---

- name: Reconfigure locales
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive locales

- name: Reconfigure tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

- name: Restart cron
  service:
    name: cron
    state: restarted

- name: Restart Postfix
  service:
    name: postfix
    state: restarted

- name: Restart sshd
  service:
    name: sshd
    state: restarted
