---

- name: Install Python passlib library
  pip:
    name: passlib
- htpasswd:
    path: /opt/xtuple/portal/.htpasswd
    name: '{{ http_auth_name }}'
    password: '{{ http_auth_pass }}'
    owner: root
    group: www-data
    mode: 0640
