---

- name: Setup {{ item.name }} security group
  ec2_group:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ aws_region }}'
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    rules: '{{ item.rules }}'
    state: present
