- hosts: deploy
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: python3

  tasks:
    - name: Copy deployment archive
      unarchive:
        src: hosts/{{ ansible_host }}/deploy/{{ deploy }}
        dest: /opt/xtuple/commerce/dev/
        owner: '{{ deployer_name }}'
        group: '{{ deployer_name }}'
