---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: python3

  pre_tasks:
    - name: Update apt cache and upgrade all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
        dpkg_options: 'force-confold,force-confdef'

  post_tasks:
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

  roles:
    - role: erp
      tags: erp
    - role: portal
      tags: portal
