= xTuple Admin Utility
:toc: left
:toclevels: 2
:icons: font
:source-highlighter: coderay
:source-language: bash

== Server provisioning with Ansible

Ansible is used for Vagrant and server provisioning.

* Ensure that Python and Python3 is installed in your system:
run `python --version` and `python3 --version`.
* Install https://pip.readthedocs.io/en/stable/installing/[Pip]:
+
[source,bash]
----
wget https://bootstrap.pypa.io/get-pip.py \
&& sudo python get-pip.py \
&& rm get-pip.py
----
* Install required Python packages: `sudo pip install -r requirements.txt`

For server provisioning only:

* Copy `config.json` file:
`cp ansible/inventory/config.json.dist ansible/inventory/config.json`.
* Config your Digital Ocean and Github tokens in
`ansible/inventory/config.json`.
* Configure customers and servers in `ansible/inventory/inventory.json`.
* Run inventory provisioning:
`ansible-playbook ansible/inventory.yml -i ansible/inventory/hosts.py`
* Copy `ansible/inventory/inventory.yml.dist` to
`ansible/inventory/inventory.yml`.
* Copy `example.xtuplecloud.com` section to `xdruple.hosts`,
provide correct domains and passwords.
* Run `ansible-playbook ansible/provision.yml -i ansible/inventory/inventory.yml --ask-become-pass`

== xTupleCommerce project setup

Once the virtual machine is up and running,
you can proceed with installation of your xTupleCommerce project(s).
Each project has a standard set of steps, yet,
it's recommended to always use the `README.adoc` file in the project itself,
in case there were any customizations.

It's recommended to start with the default
https://github.com/xtuple/flywheel[Flywheel] project.

Follow xTupleCommerce documentation to
https://github.com/xtuple/php-xdruple-commerce/blob/master/docs/index.adoc#create-a-new-project[create a new project].
