---

- stat:
    path: /usr/local/lib/node-v{{ xtau_erp_node_js.version }}-linux-x64
  register: node_path

- block:

  - name: Download NodeJS v{{ xtau_erp_node_js.version }}
    get_url:
      url: https://nodejs.org/download/release/v{{ xtau_erp_node_js.version }}/node-v{{ xtau_erp_node_js.version }}-linux-x64.tar.gz
      dest: /tmp/nodejs-v{{ xtau_erp_node_js.version }}.tar.gz
      checksum: sha256:'{{ xtau_erp_node_js.sha256 }}'

  - name: Unpack NodeJS archive
    unarchive:
      src: /tmp/nodejs-v{{ xtau_erp_node_js.version }}.tar.gz
      remote_src: yes
      dest: /usr/local/lib
      owner: root
      group: root

  - name: Remove NodeJS archive
    file:
      path: /tmp/nodejs-v{{ xtau_erp_node_js.version }}.tar.gz
      state: absent

  when: not node_path.stat.exists

- name: Setup node /usr/local/bin/node symlink
  file:
    path: /usr/local/bin/node
    src: /usr/local/lib/node-v{{ xtau_erp_node_js.version }}-linux-x64/bin/node
    state: link
    group: root
    owner: root

- name: Update npm to the latest version
  npm:
    name: npm
    global: true
    executable: /usr/local/lib/node-v{{ xtau_erp_node_js.version }}-linux-x64/bin/npm
    version: '{{ xtau_erp_npm.version }}'
