---

- name: Copy xtuple-Xvfb service script
  template:
    src: xtuple-Xvfb
    dest: /etc/init.d/xtuple-Xvfb
    mode: 0755

- shell: update-rc.d xtuple-Xvfb defaults
  register: output

- name: Start xtuple-Xvfb service
  service:
    name: xtuple-Xvfb
    state: started
